name: Docker Image CI/CD - EDS Frontend (FFT)

env:
  CONTAINER_NAME: eds-frontend-fft

on:
  schedule:
    - cron: '0 7 * * *'   # Every day at 07:00 UTC
    - cron: '0 9 * * *'   # Every day at 09:00 UTC
    - cron: '0 11 * * *'  # Every day at 11:00 UTC
    - cron: '0 13 * * *'  # Every day at 13:00 UTC
    - cron: '0 15 * * *'  # Every day at 15:00 UTC
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: SSH into VM and Deploy new Image with Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username:  ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Fail script on first error
            set -e 
            # Login to GitHub Container Registry
            echo "${{ secrets.CI_ORG_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Deploy new Image for Dev Environment
            cd /root/modapto/fft-deployment
            docker compose pull ${{ env.CONTAINER_NAME }}
            docker compose up -d --no-deps ${{ env.CONTAINER_NAME }}

            # Remove unused images
            docker image prune -f

            # Logout
            docker logout ghcr.io
